sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t pknuclei/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pknuclei/react-test npm test -- --coverage

after_success:
    - docker build -t pknuclei/multi-client ./client
    - docker build -t pknuclei/multi-nginx ./nginx
    - docker build -t pknuclei/multi-server ./server
    - docker build -t pknuclei/multi-worker ./worker
    
    # Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take the above docker images and push them to docker hub

    - docker push pknuclei/multi-client
    - docker push pknuclei/multi-nginx
    - docker push pknuclei/multi-server
    - docker push pknuclei/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: my-multi-docker
    env: MyMultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-459004692588
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY